name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install pytest pytest-cov pylint
          uv pip install -r requirements.txt

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium

      - name: Lint with pylint
        run: |
          pylint --disable=C0111,R0903,C0103,R0913,R0914,C0301,C0303,C0330,C0326,W0621,W0613 app

      - name: Test with pytest
        run: |
          pytest --cov=app tests/

  trigger-cloud-build:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Trigger Cloud Build
        run: |
          gcloud builds submit --config=cloudbuild.yaml --substitutions=_COMMIT_SHA=${{ github.sha }}
