name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: |
          pip install pytest
          pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only deploy main branch automatically
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate to Google Cloud
      # Make sure to add the GCP_SA_KEY secret in GitHub repository settings
      # This should be the JSON content of a GCP service account key with appropriate permissions
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Configure Docker for Artifact Registry'
        run: gcloud auth configure-docker us-east4-docker.pkg.dev --quiet

      - name: 'Create repository if it doesnt exist'
        run: |
          gcloud artifacts repositories create crwlr-repo --repository-format=docker --location=us-east4 --description="CRWLR server repository" || true

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          build-args: |
            BRANCH_NAME=${GITHUB_REF##*/}
          tags: us-east4-docker.pkg.dev/crwlr-server/crwlr-repo/crwlr-server:${{ github.sha }},us-east4-docker.pkg.dev/crwlr-server/crwlr-repo/crwlr-server:latest

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy crwlr-server \
            --image us-east4-docker.pkg.dev/crwlr-server/crwlr-repo/crwlr-server:${{ github.sha }} \
            --region us-east4 \
            --platform managed \
            --memory 2Gi \
            --cpu 1 \
            --timeout 3600s \
            --concurrency 80 \
            --min-instances 0 \
            --max-instances 100 \
            --allow-unauthenticated \
            --service-account github-actions-deployer@crwlr-server.iam.gserviceaccount.com \
            --set-env-vars "PROJECT_ID=crwlr-server,BRANCH_NAME=${GITHUB_REF##*/},NO_PROXY=true"
