name: CI/CD

on:
  push:
    branches: [main, dev, test]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: |
          pip install pytest
          pytest

  trigger-cloud-build:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || github.ref == 'refs/heads/dev')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Trigger Cloud Build'
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          # Set the service name based on the branch
          if [ "$BRANCH_NAME" == "main" ]; then
            CLOUD_RUN_SERVICE="crwlr-server"
          elif [ "$BRANCH_NAME" == "test" ]; then
            CLOUD_RUN_SERVICE="crwlr-server-test"
          elif [ "$BRANCH_NAME" == "dev" ]; then
            CLOUD_RUN_SERVICE="crwlr-server-dev"
          fi

          echo "Deploying from $BRANCH_NAME branch to service: $CLOUD_RUN_SERVICE"

          gcloud builds triggers run github-trigger-$BRANCH_NAME \
            --region=us-central1 \
            --branch=$BRANCH_NAME \
            --substitutions=_COMMIT_SHA=${{ github.sha }},_SERVICE_NAME=$CLOUD_RUN_SERVICE
