name: CI/CD

on:
  push:
    branches: [main, dev, test]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: |
          pip install pytest
          pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only deploy main branch automatically
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Configure Docker for GCR'
        run: gcloud auth configure-docker --quiet

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: gcr.io/crwlr-server/crwlr-server:${{ github.sha }},gcr.io/crwlr-server/crwlr-server:latest

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy crwlr-server \
            --image gcr.io/crwlr-server/crwlr-server:${{ github.sha }} \
            --region us-east4 \
            --platform managed \
            --memory 2Gi \
            --cpu 1 \
            --timeout 3600s \
            --concurrency 80 \
            --min-instances 0 \
            --max-instances 100 \
            --allow-unauthenticated \
            --service-account 662250507742-compute@developer.gserviceaccount.com \
            --set-env-vars "PROJECT_ID=crwlr-server"
