name: CI/CD

on:
  push:
    branches: [main, dev, test]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: |
          pip install pytest
          pytest

  trigger-cloud-build:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only deploy main branch automatically
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Trigger Cloud Build'
        run: |
          BRANCH_NAME="main"  # Hardcode to main since we only want main branch to auto-deploy
          CLOUD_RUN_SERVICE="crwlr-server"

          echo "Deploying from $BRANCH_NAME branch to service: $CLOUD_RUN_SERVICE"

          gcloud builds triggers run github-trigger-main \
            --region=us-central1 \
            --branch=main \
            --substitutions=_COMMIT_SHA=${{ github.sha }},_SERVICE_NAME=$CLOUD_RUN_SERVICE
